version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redoc-cli
    versions:
    - 0.10.3
    - 0.10.4
    - 0.11.1
    - 0.11.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: dompurify
    versions:
    - 2.2.6
