
# Group Assistant tasks
Everything related to the assistant part of Google Home.


## Do Not Disturb [/setup/assistant/notifications]
This is the Do Not Disturb setting in the Home app.

### Get Do Not Disturb state [POST]

  + Request

  + Response 200 (application/json)
      + Attributes
          + notifications_enabled (boolean) - Do Not Disturb state
      + Body
          { "notifications_enabled": true }

### Set Do Not Disturb state [POST]

  + Request (application/json)
      + Attributes
          + notifications_enabled (boolean) - Do Not Disturb state
      + Body
          { "notifications_enabled": true }

  + Response 200 (application/json)
      + Attributes
          + notifications_enabled (boolean) - Do Not Disturb state
      + Body
          { "notifications_enabled": true }


## Accessibility [/setup/assistant/a11y_mode]
This relates to the Accessibility settings.  

### Get accessibility state [POST]

  + Request

  + Response 200 (application/json)
      + Attributes
          + hotword_enabled (boolean) - Beep sound at start of request
          + endpoint_enabled (boolean) - Beep sound at end of request
      + Body
          {
            "endpoint_enabled": false,
            "hotword_enabled": true
          }

### Set accessibility state [POST]

  + Request

  + Response 200 (application/json)
      + Attributes
          + hotword_enabled (boolean) - Beep sound at start of request
          + endpoint_enabled (boolean) - Beep sound at end of request
      + Body
          {
            "endpoint_enabled": false,
            "hotword_enabled": true
          }


## Alarms and timers [/setup/assistant/alarms]
Get the currently set alarms and timers.

For alarms: `status`: `1` for set up and `2` for currently ringing.  
For timers: `status`: `1` for set up and `3` for currently ringing.
### Get alarms and timers [GET]

  + Request

  + Response 200 (application/json)
      + Body
          {
            "alarm": [
              {
                "date_pattern": {
                  "day": 15,
                  "month": 1,
                  "year": 2018
                },
                "time_pattern": {
                  "hour": 6,
                  "minute": 50,
                  "second": 0
                },
                "fire_time": 1515995400000.0,
                "id": "alarm/xxx",
                "status": 1,
              }
              ...
            ],
            "timer": [
              {
                "fire_time": 1516176765589,
                "id": "timer/xxx",
                "original_duration": 20000,
                "status": 1
              },
              ...
            ]
          }


## Alarms and timers volume [/setup/assistant/alarms/volume]
Get or set volume for alarms and timers. This is *not* the same as the normal volume.  
To control normal volume, there is a possible workaround (untested). See Night Mode endpoint under Device Settings on this page.

### Get alarms and timers volume [POST]

  + Request

  + Response 200 (application/json)
      + Attributes
          + volume (number) - Float value from 0 to 1 for volume
      + Body
          { "volume":0.8199999928474426 }

### Set alarms and timers volume [POST]

  + Response 200 (application/json)
      + Attributes
          + volume (number) - Float value from 0 to 1 for volume
      + Body
          { "volume":0.8199999928474426 }

  + Response 200 (application/json)
      + Attributes
          + volume (number) - Float value from 0 to 1 for volume
      + Body
          { "volume":0.8199999928474426 }


## Set equalizer settings [/setup/user_eq/set_equalizer]
Set equalizer settings.
### Set equalizer settings [POST]

  + Request (application/json)
      + Attributes
          + low_shelf (object)
              + gain_db (number) - Integer from -6 to 6 for Bass
          + high_shelf (object)
              + gain_db (number) - Integer from -6 to 6 for Treble
      + Body
          {
            "low_shelf": {
              "gain_db": 1
            },
            "high_shelf": {
              "gain_db": 1
            }
          }

  + Response 200
