
# Group Connectivity
Everything related to Wifi and Bluetooth

## Get configured networks [/setup/configured_networks]
Get a list of all saved WiFi networks (no passwords obviously)
### Get configured networks [GET]

  + Request

  + Response 200 (application/json)
      [
        {
          "ssid": "Wifi name",
          "wpa_auth": 7,
          "wpa_cipher": 4,
          "wpa_id": 0
        },
        ...
      ]


## Connect to Wifi [/setup/connect_wifi]
Connect to a new wifi network.
### Connect to Wifi [GET]
Not tested


## Get bluetooth bonded devices [/setup/bluetooth/get_bonded]
Get a list of all paired bluetooth devices.
### Get bluetooth bonded devices [GET]

  + Request

  + Response 200 (application/json)
      [
        {
          "bond_date": 1503212407260.55,
          "device_class": 5898764,
          "device_type": 1,
          "last_connect_date": 1514807829482.111,
          "mac_address": "xx: xx: xx: xx: xx: xx",
          "name": "Device Name",
          "rssi": -255,
          "service_uuids": [
            "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            ...
          ]
        }
      ]


## Set bluetooth discoverable [/setup/bluetooth/discovery]
Temporarily turn on bluetooth discoveribility. Used to connect new devices.
### Set bluetooth discoverable [POST]

  + Request (application/json)
      { "enable_discovery": true }

  + Response 200
