
# Group Connectivity
Everything related to Wifi and Bluetooth

## Get configured networks [/setup/configured_networks]
Get a list of all saved WiFi networks (no passwords obviously)
### Get configured networks [GET]

  + Request

  + Response 200 (application/json)
      [
        {
          "ssid": "Wifi name",
          "wpa_auth": 7,
          "wpa_cipher": 4,
          "wpa_id": 0
        },
        ...
      ]


## Scan for Wifi networks [/setup/scan_wifi]
**Note:** To get the results, make another request to /setup/scan_results
### Scan for Wifi networks [POST]

  + Request

  + Response 200


## Get Wifi scan results [/setup/scan_results]
### Get Wifi scan results [GET]

  + Request

  + Response 200 (application/json)
      [
        {
          "bssid": "APBSSID1",
          "signal_level": -20,
          "ssid": "APSSID1",
          "wpa_auth": 7,
          "wpa_cipher": 4,
          "wpa_id": 0
        },
        ...
      ]


## Connect to Wifi [/setup/connect_wifi]
Connect to a new wifi network.
### Connect to Wifi [POST]

  + Request
      {
        “bssid”: ”5c:0a:xx:xx:xx:xx”,
        ”signal_level”: -42,
        ”ssid”: ”myotherssid”,
        ”wpa_auth”: 7,
        ”wpa_cipher”: 4,
        ”enc_passwd”: ”xxxxxfPY=”
      }

  + Response 200


## Forget Wifi network [/setup/forget_wifi]
Forget a wifi network. Get `wpa_id` using `/setup/eureka_info`.
### Forget Wifi network [POST]

  + Request (application/json)
      { "wpa_id": 1 }

  + Response 200


## Get bluetooth bonded devices [/setup/bluetooth/get_bonded]
Get a list of all paired bluetooth devices.
### Get bluetooth bonded devices [GET]

  + Request

  + Response 200 (application/json)
      [
        {
          "bond_date": 1503212407260.55,
          "device_class": 5898764,
          "device_type": 1,
          "last_connect_date": 1514807829482.111,
          "mac_address": "xx:xx:xx:xx:xx:xx",
          "name": "Device Name",
          "rssi": -255,
          "service_uuids": [
            "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            ...
          ]
        }
      ]


## Forget bluetooth bonded device [/setup/bluetooth/bond]
Forget a paired bluetooth device.
### Forget bluetooth bonded device [POST]

  + Request (application/json)
      {
        "mac_address": "xx:xx:xx:xx:xx:xx",
        "bond": false
      }

  + Response 200

## Set bluetooth discoverable [/setup/bluetooth/discovery]
Temporarily turn on bluetooth discoveribility. Used to connect new devices.
### Set bluetooth discoverable [POST]

  + Request (application/json)
      { "enable_discovery": true }

  + Response 200

## Connect / Disconnect bluetooth device [/setup/bluetooth/connect]
Connect or disconnect an existing bluetooth device. To disconnect, send `false` instead of `true`.  
If `mac_address` and `profile` are provided, then it will define the default Bluetooth device.  
The `{connect:true/false}` only will just connect/disconnect from the default device defined before.
**Note:** This is not the same as pairing and forgetting a device.
### Connect / Disconnect bluetooth device [POST]

  + Request (application/json)
      {
        "mac_address": "xx:xx:xx:xx:xx:xx",
        "profile": 2,
        "connect": true
      }

  + Response 200

