
# Group Device Info
Get all kinds of info.

## Get app device id [/setup/get_app_device_id]
Not used anywhere locally. Must be related to one of the cloud functions.
### Get app device id [POST]

  + Request (application/json)
      { "app_id": "E8C28D3C" }

  + Response 200 (application/json)
      {
        "app_device_id": "xxxxx",
        "certificate": "-----BEGIN CERTIFICATE-----\nxxxxxx\n-----END CERTIFICATE-----\n",
        "signed_data": "xxxxx"
      }


## Get offers [/setup/offer]
Gets a token which can presumably be used to get offers online. Not used anywhere locally.
### Get offers [GET]

  + Request

  + Response 200 (application/json)
      {
        "token": "xxxxxqR8aQ=="
      }


## Get device info [/setup/eureka_info?{options}=detail&{params}=]
Get information about device and some states.
**Note:**
params: Comma separated combination of these values: `version,audio,name,build_info,detail,device_info,net,wifi,setup,settings,opt_in,opencast,multizone,proxy,night_mode_params,user_eq,room_equalizer`
### Get device info [GET]

  + Parameters
      + params
      + options

  + Request
    ?params=version,audio,name,build_info,detail,device_info,net,wifi,setup,settings,opt_in,opencast,multizone,proxy,night_mode_params,user_eq,room_equalizer&options=detail

  + Response 200 (application/json)
      {
        "build_info": {
          "build_type": 2,
          "cast_build_revision": "1.29.106111",
          "cast_control_version": 1,
          "preview_channel_state": 4,
          "release_track": "preview-joining-stable-channel",
          "system_build_number": "106111"
        },
        "audio": {
          "digital": false
        },
        "detail": {
          "icon_list": [{
            "depth": 32,
            "height": 55,
            "mimetype": "image/png",
            "url": "/setup/icon.png",
            "width": 98
          }],
          "locale": {
            "display_string": "English (United States)"
          },
          "timezone": {
            "display_string": "India Standard Time (Kolkata)",
            "offset": 330
          }
        },
        "device_info": {
        "4k_blocked": 0,
        "capabilities": {
          "assistant_supported": true,
          "audio_hdr_supported": false,
          "ble_supported": true,
          "bluetooth_audio_sink_supported": true,
          "bluetooth_audio_source_supported": false,
          "bluetooth_supported": true,
          "cloudcast_supported": true,
          "display_supported": false,
          "fdr_supported": false,
          "hdmi_prefer_50hz_supported": false,
          "hdmi_prefer_high_fps_supported": false,
          "hi_res_audio_supported": false,
          "hotspot_supported": true,
          "input_management_supported": true,
          "multi_user_supported": true,
          "multichannel_group_supported": false,
          "multizone_supported": true,
          "night_mode_supported": true,
          "night_mode_supported_v2": true,
          "opencast_supported": true,
          "preview_channel_supported": true,
          "proxy_server_supported": false,
          "reboot_supported": true,
          "remote_ducking_supported": true,
          "setup_supported": true,
          "show_debug_overlay_supported": false,
          "stats_supported": true,
          "system_sound_effects_supported": false,
          "ui_flipping_supported": false,
          "user_eq_supported": true,
          "wifi_regulatory_domain_locked": true,
          "wifi_supported": true
        },
        "cloud_device_id": "00XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXD3",
        "factory_country_code": "US",
        "hotspot_bssid": "XX:XX:XX:XX:XX:XX",
        "mac_address": "XX:XX:XX:XX:XX:X",
        "manufacturer": "Google Inc.",
        "model_name": "Google Home",
        "product_name": "pineapple",
        "public_key": "xxxxx",
        "ssdp_udn": "xxxxx",
        "uma_client_id": "xxxxx",
        "uptime": 13279.28
        },
        "multizone": {
          "audio_output_delay": 0.0,
          "audio_output_delay_oem": 0.0,
          "aux_in_group": "",
          "groups": [],
          "multichannel_status": 0
        },
        "name": "Living Room speaker",
        "net": {
          "ethernet_connected": false,
          "ip_address": "192.168.XXX.XXX",
          "online": true
        },
        "night_mode_params": {
          "do_not_disturb": false,
          "enabled": true,
          "led_brightness": 0.5,
          "volume": 0.4,
          "windows": [
            {
              "days": [0, 1, 2, 3, 4, 5, 6],
              "length_hours": 8.0,
              "start_hour": 22.0
            }
          ]
        },
        "opencast": {
          "pin_code": "4530"
        },
        "opt_in": {
          "audio_hdr": false,
          "autoplay_on_signal": true,
          "cloud_ipc": true,
          "hdmi_prefer_50hz": false,
          "hdmi_prefer_high_fps": true,
          "location": false,
          "opencast": true,
          "preview_channel": true,
          "remote_ducking": true,
          "stats": true,
          "ui_flipped": false
        },
        "proxy": {
          "mode": "system"
        },
        "settings": {
          "closed_caption": {},
          "control_notifications": 1,
          "country_code": "IN",
          "locale": "en-US",
          "network_standby": 0,
          "system_sound_effects": true,
          "time_format": 1,
          "timezone": "Asia/Kolkata",
          "wake_on_cast": 1
        },
        "setup": {
          "setup_state": 60,
          "ssid_suffix": "k",
          "stats": {
            "num_check_connectivity": 0,
            "num_connect_wifi": 0,
            "num_connected_wifi_not_saved": 0,
            "num_initial_eureka_info": 0,
            "num_obtain_ip": 0
          },
          "tos_accepted": true
        },
        "user_eq": {
          "high_shelf": {
            "frequency": 4500.0,
            "gain_db": 0.0,
            "quality": 0.707
          },
          "low_shelf": {
            "frequency": 150.0,
            "gain_db": 0.0,
            "quality": 0.707
          },
          "max_peaking_eqs": 0,
          "peaking_eqs": []
        },
        "version": 9,
        "wifi": {
          "bssid": "xx:xx:xx:xx:xx:xx",
          "has_changes": false,
          "noise_level": -92,
          "signal_level": -42,
          "ssid": "Wifi name",
          "wpa_configured": true,
          "wpa_id": 1,
          "wpa_state": 10
        }
      }


## Check Ready Status [/setup/assistant/check_ready_status]
Setting `play_ready_message` to true plays a welcome message on the device saying "Hi, I'm your Google Assistant. I'm here to help. To learn a few things you can do, continue in the Google Home app."
### Check Ready Status [POST]

  + Request (application/json)
      {
        "play_ready_message": false
      }

  + Response 200 (application/json)
      {
        "can_enroll": true,
        "enrollment_state": 0,
        "error_code": 0,
        "ready": true
      }

  + Request (application/json)
      {
        "play_ready_message": false,
        "user_id": "xxxxx"
      }
  
  + Response 200 (application/json)
      {
        "can_enroll": true,
        "enrollment_state": 0,
        "error": "NOT_LINKED",
        "error_code": 0,
        "ready": false,
        "retryable": false
      }


## Get supported timezones [/setup/supported_timezones]
Get a list of supported timezones. Used while setting Night Mode.
### Get supported timezones [GET]

  + Request

  + Response 200 (application/json)
      [
        {
          "display_string": "Samoa Standard Time (Midway)",
          "offset": -660,
          "timezone": "Pacific/Midway"
        }, {
          "display_string": "Hawaii-Aleutian Standard Time (Honolulu)",
          "offset": -600,
          "timezone": "Pacific/Honolulu"
        }, {
          "display_string": "Alaska Standard Time (Anchorage)",
          "offset": -540,
          "timezone": "America/Anchorage"
        },
        ...
      ]


## Get supported locales [/setup/supported_locales]
Get a list of supported locales. Used while setting Night Mode.
### Get supported locales [GET]

  + Request

  + Response 200 (application/json)
      [
        {
          "display_string": "English (United States)",
          "locale": "en-US"
        }, {
        {
          "display_string": "German - Deutsch",
          "locale": "de"
        }, {
        {
          "display_string": "English (United Kingdom)",
          "locale": "en-GB"
        },
        ...
      ]
