
# Group Device Settings
Change various device settings

## Set device options [/setup/set_eureka_info]
**Note:** Any combination of fields can be used.
### Set device options [POST]

  + Request (application/json)
      {
        "name": "Living Room",
        "settings": {
          "control_notifications": 2
        },
        "opt_in": {
          "opencast": false,
          "preview_channel": false,
          "remote_ducking": false,
          "stats": false
        }
      }

  + Response 200


## Set night mode settings [/setup/assistant/set_night_mode_params]
Set night mode settings.
**Note:** Any combination of fields can be used.

**Control normal volume with night mode**  
Since normal volume can be controlled for night mode, if night mode is active throughout the day, it might be possible to use it as a workaround for controlling normal volume. [_Testing needed_]
### Set night mode settings [POST]

  + Request (application/json)
      {
        "enabled": false,
        "do_not_disturb": true,
        "led_brightness": 0.44999998807907104,
        "volume":0.46000000834465027,
        "demo_to_user": true,
        "windows": [
          {
            "length_hours": 8,
            "days": [0,1,2,3,4,5,6],
            "start_hour": 22
          }
        ]
      }

  + Response 200

## Join group [/setup/multizone/leave_group]
Join a multizone group.
**Note:**
uuid can be found at /setup/eureka_info?params=multizone
### Join group [POST]
Not tested

## Leave group [/setup/multizone/leave_group]
Leave a multizone group.
**Note:**
uuid can be found at /setup/eureka_info?params=multizone
### Leave group [POST]

  + Request (application/json)
      { "uuid": "< MULTIZONE GROUP UUID >" }

  + Response 200

## Disband group [/setup/multizone/leave_group]
Disband (delete) a multizone group.
**Note:**
uuid can be found at /setup/eureka_info?params=multizone
### Disband group [POST]

  + Request (application/json)
      { "uuid": "< MULTIZONE GROUP UUID >" }

  + Response 200


## Reboot device [/setup/reboot]
Reboot the device.
### Reboot the device [POST]

  + Request (application/json)
      { "params": "now" }

  + Response 200


## Factory reset device [/setup/reboot]
Factory reset the device.
### Factory reset device [POST]

  + Request (application/json)
      { "params": "fdr" }

  + Response 200
