FORMAT:  1A

# Group Device Settings

## Set device options [/setup/set_eureka_info]
**Note:** Any combination of fields can be used.
### Set device options [POST]

  + Request (application/json)
      {
        "name": "Living Room",
        "settings": {
          "control_notifications": 2
        },
        "opt_in": {
          "opencast": false,
          "preview_channel": false,
          "remote_ducking": false,
          "stats": false
        }
      }

  + Response 200


## Set night mode settings [/setup/assistant/set_night_mode_params]
**Note:** Any combination of fields can be used.
### Set night mode settings [POST]

  + Request (application/json)
      {
        "enabled": false,
        "do_not_disturb": true,
        "led_brightness": 0.44999998807907104,
        "demo_to_user": true,
        "windows": [
          {
            "length_hours": 8,
            "days": [0,1,2,3,4,5,6],
            "start_hour": 22
          }
        ]
      }

  + Response 200


## Reboot device [/setup/reboot]
### Get configured networks [POST]
Not tested
