
# Google Home Local API

This is an unofficial documentation of the local API.
To contribute, take a look at [the GitHub repo](https://github.com/rithvikvibhu/GHLocalApi)

<!-- include(assistant.apib) -->
<!-- include(connectivity.apib) -->
<!-- include(device-info.apib) -->
<!-- include(device-settings.apib) -->
